/**
 * api.js — Dradis proxy router
 *
 * All routes validate their inputs before touching the upstream API.
 * Errors from DradisClient are translated to appropriate HTTP status codes.
 *
 * Route summary:
 *   GET /api/status                          — health check
 *   GET /api/projects                        — list all projects
 *   GET /api/projects/:id/document_properties
 *   GET /api/projects/:id/issues
 */

import { Router } from 'express';
import { DradisApiError } from '../services/dradisClient.js';

/**
 * Validate that a route parameter is a safe positive integer.
 * Rejects strings like "0", negative numbers, floats, and path-traversal attempts.
 *
 * @param {string} value - Raw value from req.params
 * @returns {number|null} - Parsed integer, or null if invalid
 */
function parseProjectId(value) {
  // Must be a string of digits only — no decimals, signs, or other chars
  if (!/^\d+$/.test(value)) return null;
  const n = parseInt(value, 10);
  return n > 0 ? n : null;
}

/**
 * Translate a client error into an HTTP status code.
 * DradisApiErrors carry the upstream status; all other errors are 502.
 *
 * @param {Error} err
 * @returns {number}
 */
function statusForError(err) {
  if (err instanceof DradisApiError) {
    // Forward 401/403/404 from Dradis as-is; everything else is our 502
    if ([401, 403, 404].includes(err.statusCode)) return err.statusCode;
  }
  return 502;
}

/**
 * Return a client-safe error message.
 * Full error detail (including any upstream response body) is logged server-side.
 * We never reflect upstream content back to the browser — it may contain
 * internal paths, tokens, or other sensitive information from Dradis.
 *
 * @param {Error} err
 * @returns {string}
 */
function safeMessage(err) {
  if (err instanceof DradisApiError) {
    // Safe to tell the client the HTTP status, but not the upstream body
    return `Upstream Dradis error (HTTP ${err.statusCode})`;
  }
  // For TLS and network errors, the message is generated by our own code
  // and is safe to surface (it contains only our own text, not upstream content)
  if (err.message?.startsWith('TLS error') ||
      err.message?.startsWith('Dradis request timed out') ||
      err.message?.startsWith('Dradis response exceeded')) {
    return err.message;
  }
  return 'Failed to reach Dradis — check server logs for details';
}


/**
 * Build and return the Express router.
 * Receives the DradisClient instance via dependency injection rather than
 * importing a singleton — makes routes unit-testable without mocking modules.
 *
 * @param {import('../services/dradisClient.js').DradisClient} dradisClient
 * @param {string} host - Dradis host URL (surfaced in /api/status only)
 * @returns {Router}
 */
export function createApiRouter(dradisClient, host) {
  const router = Router();

  // ── Health check ────────────────────────────────────────────────────────────
  // Lets the frontend confirm the server is running and configured.
  // Never exposes the API token — only confirms it is set.
  router.get('/status', (_req, res) => {
    res.json({
      ok:              true,
      host,
      tokenConfigured: true, // server would have exited at startup if token was missing
    });
  });

  // ── Projects ────────────────────────────────────────────────────────────────
  router.get('/projects', async (_req, res) => {
    try {
      const projects = await dradisClient.getProjects();
      res.json(projects);
    } catch (err) {
      // Log full detail (including any upstream response body) server-side only.
      // Never reflect upstream error bodies to the client — they may contain
      // sensitive information from the Dradis server.
      res.log.error({ err }, 'Failed to fetch projects');
      res.status(statusForError(err)).json({ error: safeMessage(err) });
    }
  });

  // ── Document properties ─────────────────────────────────────────────────────
  router.get('/projects/:id/document_properties', async (req, res) => {
    const projectId = parseProjectId(req.params.id);
    if (projectId === null) {
      return res.status(400).json({ error: 'Invalid project ID' });
    }

    try {
      const props = await dradisClient.getDocumentProperties(projectId);
      res.json(props);
    } catch (err) {
      res.log.error({ err, projectId }, 'Failed to fetch document properties');
      res.status(statusForError(err)).json({ error: safeMessage(err) });
    }
  });

  // ── Issues ──────────────────────────────────────────────────────────────────
  router.get('/projects/:id/issues', async (req, res) => {
    const projectId = parseProjectId(req.params.id);
    if (projectId === null) {
      return res.status(400).json({ error: 'Invalid project ID' });
    }

    try {
      const issues = await dradisClient.getIssues(projectId);
      res.json(issues);
    } catch (err) {
      res.log.error({ err, projectId }, 'Failed to fetch issues');
      res.status(statusForError(err)).json({ error: safeMessage(err) });
    }
  });

  return router;
}
